//0
// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("0.6.5.0")]
[assembly: AssemblyVersion("0.6.5.0")]

namespace KerbalMechanics
{
    public static class Version
    {
        public const int major = 0;
        public const int minor = 6;
        public const int patch = 5;
        public const int build = 0;
        public const string Number = "0.6.5.0";
#if DEBUG
        public const string Text = Number + " DEBUG";
#else
		public const string Text = Number + "";
#endif
    }
}